baseURL = "https://natescode.com/"
languageCode = "en-us"
title = "natescode.com"
theme = "terminal"
timeZone = "America/Chicago"
# paginate = 10

[[menus.main]]
identifier = "about"
name = "About"
url = "/about.html"
weight = 20

[[menus.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 30

[[menus.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 40

[permalinks]
blog = "/blog/:year/:month/:day/:title/"

[taxonomies]
tag = "tags"
author = "authors"

[indexes]
tag = "tags"

# [markup]
# defaultMarkdownHandler = "goldmark"

# [markup.goldmark]
# smartypants = true
# fractions = true
# superscript = true
# unsafe = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
disqus = "mydisquscode"

[[params.social]]
name = "github"
url = "https://github.com/natescode"

[[params.social]]
name = "x"
url = "https://x.com/natescode"

[[params.social]]
name = "youtube"
url = "https://youtube.com/natescode"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/natescode"

[[params.social]]
name = "buy me a coffee"
url = "https://www.buymeacoffee.com/natescode"

[module.hugoVersion]
extended = false
min = "0.116.0"
